### ISSUE TITLE
Bloop IO scheduler gets shut down after successful test run

### ISSUE THREAD

**Issue by olafurpg** [olafurpg/bsp-pants#11]
First setup the repo like this
```
git clone -b io-scheduler https://github.com/olafurpg/intellij-bsp-pants
cd intellij-bsp-pants
./setup-bsp.sh
```

Next, reproduce the issue
```sh
❯ bloop test src/test/scala/foo:foo
Compiling src/test/scala/foo:foo (1 Scala source)
Compiled src/test/scala/foo:foo (2916ms)
foo.MySuite:
Auto-test!
+ auto-test works 0.031s
Execution took 31ms
1 tests, 1 passed
All tests in foo.MySuite passed

===============================================
Total duration: 31ms
All 1 test suites passed.
===============================================
❯ bloop test src/test/scala/foo:foo
error: Unexpected error forces client exit!
java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:397)
	at bloop.shaded.snailgun.protocol.Protocol.$anonfun$processChunkFromServer$1(Protocol.scala:181)
	at scala.util.Try$.apply(Try.scala:213)
	at bloop.shaded.snailgun.protocol.Protocol.processChunkFromServer(Protocol.scala:180)
	at bloop.shaded.snailgun.protocol.Protocol.sendCommand(Protocol.scala:108)
	at bloop.shaded.snailgun.TcpClient.run(TcpClient.scala:34)
	at bloop.bloopgun.BloopgunCli.executeCmd$1(Bloopgun.scala:255)
	at bloop.bloopgun.BloopgunCli.fireCommand(Bloopgun.scala:261)
	at bloop.bloopgun.BloopgunCli.run(Bloopgun.scala:216)
	at bloop.bloopgun.Bloopgun$.main(Bloopgun.scala:560)
	at bloop.bloopgun.Bloopgun.main(Bloopgun.scala)
```

**Comment by olafurpg** [comment]
Here is `jstack` output before the error happens (https://gist.github.com/olafurpg/bb1145266a14bdb0cecb847c8d1fb2b9) and after the error happens (https://gist.github.com/olafurpg/2991e1fa154f02afeda958609c72759e). The difference is that the following threads no longer exist after the error

```
"bloop-io-42" #42 daemon prio=5 os_prio=31 tid=0x00007faf37f34000 nid=0x7403 waiting on condition [0x0000700004e7a000]
```

I tried to find out how those threads got killed by attaching the IntelliJ debugger to the bloop process.
```
❯ cat ~/.bloop/.jvmopts
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
```
Run "View breakpoints" action in IntelliJ and enable "all uncaught JVM exceptions"

<img width="637" alt="Screenshot 2020-01-28 at 17 55 50" src="https://user-images.githubusercontent.com/1408093/73291099-7098a180-41f7-11ea-91aa-9d9e5d9445aa.png">

Run "Attach process" and select bloop (on a clean server instance before error)

Run `bloop test src/test/scala/foo:foo` to reproduce the issue and see where IntelliJ stops on the uncaught exception

<img width="1395" alt="Screenshot 2020-01-28 at 16 51 37" src="https://user-images.githubusercontent.com/1408093/73291161-91f98d80-41f7-11ea-9794-285fa9bd0324.png">
